version: "3"
services:
  minecraft:
    image: itzg/minecraft-server
    container_name: mc-server
    network_mode: "host" 

    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.21.11"
      MEMORY: "4G"
      NETWORK_COMPRESSION_THRESHOLD: "64"
      MAX_TICK_TIME: "-1"    
      USE_AIKAR_FLAGS: "true"
      MOTD: "SDA Project Server"
      ONLINE_MODE: "false"

    restart: unless-stopped
    
    volumes:
      - ./data:/data